import { Security } from 'src/app/models/security.model';

export const securities: Security[] = [
    {
        SecurityName: 'אאורה',
        Symbol: 'אאורה',
        SecurityId: 373019,
        SecurityType: 'מניות',
        ClosingPrice: 487.50,
        rating: 2,
        PercentageChange: '0.41%',
        LastTransactionTime: 'סוף יום',
        SecuritiesAmount: 15,
        ManagingBank: 'לאומי',
        AccountNumber: '459-6565',
        selected: false
    },
    {
        SecurityName: 'אאורה אגח י',
        Symbol: 'אארה.ק10',
        SecurityId: 3730413,
        SecurityType: 'איגרות חוב',
        ClosingPrice: 101.72,
        rating: 2,
        PercentageChange: '0.04%',
        LastTransactionTime: 'סוף יום',
        SecuritiesAmount: 30,
        ManagingBank: 'לאומי',
        AccountNumber: '459-6565',
        selected: false
    },
    {
        SecurityName: 'אאורה',
        Symbol: 'אאורה',
        SecurityId: 373019,
        SecurityType: 'מניות',
        ClosingPrice: 487.50,
        rating: 2,
        PercentageChange: '0.41%',
        LastTransactionTime: 'סוף יום',
        SecuritiesAmount: 15,
        ManagingBank: 'לאומי',
        AccountNumber: '459-6565',
        selected: false
    },
    {
        SecurityName: 'אאורה אגח י',
        Symbol: 'אארה.ק10',
        SecurityId: 3730413,
        SecurityType: 'איגרות חוב',
        ClosingPrice: 101.72,
        rating: 2,
        PercentageChange: '0.04%',
        LastTransactionTime: 'סוף יום',
        SecuritiesAmount: 30,
        ManagingBank: 'לאומי',
        AccountNumber: '459-6565',
        selected: false
    },
    {
        SecurityName: 'אאורה',
        Symbol: 'אאורה',
        SecurityId: 373019,
        SecurityType: 'מניות',
        ClosingPrice: 487.50,
        rating: 2,
        PercentageChange: '0.41%',
        LastTransactionTime: 'סוף יום',
        SecuritiesAmount: 15,
        ManagingBank: 'לאומי',
        AccountNumber: '459-6565',
        selected: false
    },
    {
        SecurityName: 'אאורה אגח י',
        Symbol: 'אארה.ק10',
        SecurityId: 3730413,
        SecurityType: 'איגרות חוב',
        ClosingPrice: 101.72,
        rating: 2,
        PercentageChange: '0.04%',
        LastTransactionTime: 'סוף יום',
        SecuritiesAmount: 30,
        ManagingBank: 'לאומי',
        AccountNumber: '459-6565',
        selected: false
    },
    {
        SecurityName: 'אאורה',
        Symbol: 'אאורה',
        SecurityId: 373019,
        SecurityType: 'מניות',
        ClosingPrice: 487.50,
        rating: 2,
        PercentageChange: '0.41%',
        LastTransactionTime: 'סוף יום',
        SecuritiesAmount: 15,
        ManagingBank: 'לאומי',
        AccountNumber: '459-6565',
        selected: false
    },
    {
        SecurityName: 'אאורה אגח י',
        Symbol: 'אארה.ק10',
        SecurityId: 3730413,
        SecurityType: 'איגרות חוב',
        ClosingPrice: 101.72,
        rating: 2,
        PercentageChange: '0.04%',
        LastTransactionTime: 'סוף יום',
        SecuritiesAmount: 30,
        ManagingBank: 'לאומי',
        AccountNumber: '459-6565',
        selected: false
    }
];
